package enum Harness
{
    package static var script: String
    {
        [
            "(function()",
            "{",
            "    function rgb(s)",
            "    {",
            "        var re = /(\\d+), (\\d+), (\\d+)(?:, ([\\d.]+))?/",
            "        var m = String(s).match(re)",
            "        if (!m) return null",
            "        if (m[4] !== undefined && +m[4] < 0.05)",
            "        {",
            "            return null",
            "        }",
            "        return { r: +m[1], g: +m[2], b: +m[3] }",
            "    }",
            "    function hex(h)",
            "    {",
            "        h = String(h).trim().replace(\"#\", \"\")",
            "        if (h.length !== 6) return null",
            "        return {",
            "            r: parseInt(h.slice(0, 2), 16),",
            "            g: parseInt(h.slice(2, 4), 16),",
            "            b: parseInt(h.slice(4, 6), 16)",
            "        }",
            "    }",
            "    function lin(c)",
            "    {",
            "        c = c / 255",
            "        return c <= 0.04045 ? c / 12.92",
            "            : Math.pow((c + 0.055) / 1.055, 2.4)",
            "    }",
            "    function lum(c)",
            "    {",
            "        return 0.2126 * lin(c.r) + 0.7152 * lin(c.g)",
            "            + 0.0722 * lin(c.b)",
            "    }",
            "    function ratio(a, b)",
            "    {",
            "        var x = lum(a), y = lum(b)",
            "        var hi = Math.max(x, y), lo = Math.min(x, y)",
            "        return (hi + 0.05) / (lo + 0.05)",
            "    }",
            "    function same(a, b)",
            "    {",
            "        return a && b && a.r === b.r && a.g === b.g",
            "            && a.b === b.b",
            "    }",
            "    function under(el)",
            "    {",
            "        var e = el",
            "        while (e)",
            "        {",
            "            var c = rgb(getComputedStyle(e).backgroundColor)",
            "            if (c) return c",
            "            e = e.parentElement",
            "        }",
            "        return { r: 255, g: 255, b: 255 }",
            "    }",
            "    var root = getComputedStyle(document.documentElement)",
            "    var name = \"--manuscript-insetBackground\"",
            "    var inset = hex(root.getPropertyValue(name))",
            "    var sel =",
            "    [",
            "        \".highlight pre\", \".highlight code\",",
            "        \".chroma pre\", \".codehilite pre\",",
            "        \"pre[class*=language-]\", \"code[class*=language-]\",",
            "        \"pre.hljs\", \"code.hljs\", \".hljs\"",
            "    ]",
            "    var blocks = []",
            "    sel.forEach(function(s)",
            "    {",
            "        document.querySelectorAll(s).forEach(function(e)",
            "        {",
            "            if (blocks.indexOf(e) === -1) blocks.push(e)",
            "        })",
            "    })",
            "    var grounded = 0, ungrounded = 0",
            "    blocks.forEach(function(b)",
            "    {",
            "        var c = rgb(getComputedStyle(b).backgroundColor)",
            "        if (same(c, inset)) grounded++",
            "        else ungrounded++",
            "    })",
            "    var seen = []",
            "    blocks.forEach(function(b)",
            "    {",
            "        b.querySelectorAll(\"span\").forEach(function(s)",
            "        {",
            "            if (s.children.length) return",
            "            if (!s.textContent.trim()) return",
            "            if (seen.indexOf(s) === -1) seen.push(s)",
            "        })",
            "    })",
            "    var worst = 99, spans = 0, low = 0",
            "    seen.forEach(function(s)",
            "    {",
            "        var fg = rgb(getComputedStyle(s).color)",
            "        if (!fg) return",
            "        var r = ratio(fg, under(s))",
            "        spans++",
            "        if (r < 3) low++",
            "        if (r < worst) worst = r",
            "    })",
            "    var ours =",
            "    [",
            "        \".token.keyword\", \".highlight .k\", \".chroma .k\"",
            "    ]",
            "    var collateral = 0, orphan = 0",
            "    ours.forEach(function(s)",
            "    {",
            "        document.querySelectorAll(s).forEach(function(e)",
            "        {",
            "            var host = e.closest(\"pre, code\")",
            "            if (!host) { collateral++; return }",
            "            if (blocks.indexOf(host) === -1) return",
            "            var c = rgb(getComputedStyle(host).backgroundColor)",
            "            if (!same(c, inset)) orphan++",
            "        })",
            "    })",
            "    function dark(v)",
            "    {",
            "        return String(v || \"\").trim().toLowerCase()",
            "            === \"dark\"",
            "    }",
            "    var h = document.documentElement, y = document.body",
            "    var siteDark = h.classList.contains(\"dark\")",
            "        || (y && y.classList.contains(\"dark\"))",
            "        || dark(h.getAttribute(\"data-theme\"))",
            "    var weDark =",
            "        matchMedia(\"(prefers-color-scheme: dark)\").matches",
            "    return JSON.stringify(",
            "    {",
            "        blocks: blocks.length, grounded: grounded,",
            "        ungrounded: ungrounded, spans: spans, under: low,",
            "        worst: Math.round(worst * 100) / 100,",
            "        collateral: collateral, orphan: orphan,",
            "        siteDark: siteDark, weDark: weDark",
            "    })",
            "})()"
        ]
        .joined(separator: "\n")
    }
}
